// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64 || wasm

package ebpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type dnsrecvStash struct {
	_   structs.HostLayout
	Buf uint64
}

// Names of all BPF objects in the ELF.
//
// Used for safe lookups in a Collection or CollectionSpec.
const (
	dnsrecvMapEvents                  = "events"
	dnsrecvMapPending                 = "pending"
	dnsrecvProgMochiTcpRecvmsgEnter   = "mochi_tcp_recvmsg_enter"
	dnsrecvProgMochiTcpRecvmsgExit    = "mochi_tcp_recvmsg_exit"
	dnsrecvProgMochiUdpRecvmsgEnter   = "mochi_udp_recvmsg_enter"
	dnsrecvProgMochiUdpRecvmsgExit    = "mochi_udp_recvmsg_exit"
	dnsrecvProgMochiUdpv6RecvmsgEnter = "mochi_udpv6_recvmsg_enter"
	dnsrecvProgMochiUdpv6RecvmsgExit  = "mochi_udpv6_recvmsg_exit"
)

// loadDnsrecv returns the embedded CollectionSpec for dnsrecv.
func loadDnsrecv() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_DnsrecvBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load dnsrecv: %w", err)
	}

	return spec, err
}

// loadDnsrecvObjects loads dnsrecv and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*dnsrecvObjects
//	*dnsrecvPrograms
//	*dnsrecvMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadDnsrecvObjects(obj any, opts *ebpf.CollectionOptions) error {
	spec, err := loadDnsrecv()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// dnsrecvSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type dnsrecvSpecs struct {
	dnsrecvProgramSpecs
	dnsrecvMapSpecs
	dnsrecvVariableSpecs
}

// dnsrecvProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type dnsrecvProgramSpecs struct {
	MochiTcpRecvmsgEnter   *ebpf.ProgramSpec `ebpf:"mochi_tcp_recvmsg_enter"`
	MochiTcpRecvmsgExit    *ebpf.ProgramSpec `ebpf:"mochi_tcp_recvmsg_exit"`
	MochiUdpRecvmsgEnter   *ebpf.ProgramSpec `ebpf:"mochi_udp_recvmsg_enter"`
	MochiUdpRecvmsgExit    *ebpf.ProgramSpec `ebpf:"mochi_udp_recvmsg_exit"`
	MochiUdpv6RecvmsgEnter *ebpf.ProgramSpec `ebpf:"mochi_udpv6_recvmsg_enter"`
	MochiUdpv6RecvmsgExit  *ebpf.ProgramSpec `ebpf:"mochi_udpv6_recvmsg_exit"`
}

// dnsrecvMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type dnsrecvMapSpecs struct {
	Events  *ebpf.MapSpec `ebpf:"events"`
	Pending *ebpf.MapSpec `ebpf:"pending"`
}

// dnsrecvVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type dnsrecvVariableSpecs struct {
}

// dnsrecvObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadDnsrecvObjects or ebpf.CollectionSpec.LoadAndAssign.
type dnsrecvObjects struct {
	dnsrecvPrograms
	dnsrecvMaps
	dnsrecvVariables
}

func (o *dnsrecvObjects) Close() error {
	return _DnsrecvClose(
		&o.dnsrecvPrograms,
		&o.dnsrecvMaps,
	)
}

// dnsrecvMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadDnsrecvObjects or ebpf.CollectionSpec.LoadAndAssign.
type dnsrecvMaps struct {
	Events  *ebpf.Map `ebpf:"events"`
	Pending *ebpf.Map `ebpf:"pending"`
}

func (m *dnsrecvMaps) Close() error {
	return _DnsrecvClose(
		m.Events,
		m.Pending,
	)
}

// dnsrecvVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadDnsrecvObjects or ebpf.CollectionSpec.LoadAndAssign.
type dnsrecvVariables struct {
}

// dnsrecvPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadDnsrecvObjects or ebpf.CollectionSpec.LoadAndAssign.
type dnsrecvPrograms struct {
	MochiTcpRecvmsgEnter   *ebpf.Program `ebpf:"mochi_tcp_recvmsg_enter"`
	MochiTcpRecvmsgExit    *ebpf.Program `ebpf:"mochi_tcp_recvmsg_exit"`
	MochiUdpRecvmsgEnter   *ebpf.Program `ebpf:"mochi_udp_recvmsg_enter"`
	MochiUdpRecvmsgExit    *ebpf.Program `ebpf:"mochi_udp_recvmsg_exit"`
	MochiUdpv6RecvmsgEnter *ebpf.Program `ebpf:"mochi_udpv6_recvmsg_enter"`
	MochiUdpv6RecvmsgExit  *ebpf.Program `ebpf:"mochi_udpv6_recvmsg_exit"`
}

func (p *dnsrecvPrograms) Close() error {
	return _DnsrecvClose(
		p.MochiTcpRecvmsgEnter,
		p.MochiTcpRecvmsgExit,
		p.MochiUdpRecvmsgEnter,
		p.MochiUdpRecvmsgExit,
		p.MochiUdpv6RecvmsgEnter,
		p.MochiUdpv6RecvmsgExit,
	)
}

func _DnsrecvClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed dnsrecv_bpfel.o
var _DnsrecvBytes []byte
