// Code generated by bpf2go; DO NOT EDIT.
//go:build mips || mips64 || ppc64 || s390x

package ebpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type tcpstreamStreamStash struct {
	_    structs.HostLayout
	Segs [4]struct {
		_    structs.HostLayout
		Base uint64
		Len  uint32
		_    [4]byte
	}
	Nsegs uint8
	Pad   [7]uint8
}

// Names of all BPF objects in the ELF.
//
// Used for safe lookups in a Collection or CollectionSpec.
const (
	tcpstreamMapEvents                = "events"
	tcpstreamMapPending               = "pending"
	tcpstreamProgMochiStreamRecvEnter = "mochi_stream_recv_enter"
	tcpstreamProgMochiStreamRecvExit  = "mochi_stream_recv_exit"
	tcpstreamProgMochiStreamSendEnter = "mochi_stream_send_enter"
	tcpstreamProgMochiStreamSendExit  = "mochi_stream_send_exit"
)

// loadTcpstream returns the embedded CollectionSpec for tcpstream.
func loadTcpstream() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_TcpstreamBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load tcpstream: %w", err)
	}

	return spec, err
}

// loadTcpstreamObjects loads tcpstream and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*tcpstreamObjects
//	*tcpstreamPrograms
//	*tcpstreamMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadTcpstreamObjects(obj any, opts *ebpf.CollectionOptions) error {
	spec, err := loadTcpstream()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// tcpstreamSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type tcpstreamSpecs struct {
	tcpstreamProgramSpecs
	tcpstreamMapSpecs
	tcpstreamVariableSpecs
}

// tcpstreamProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type tcpstreamProgramSpecs struct {
	MochiStreamRecvEnter *ebpf.ProgramSpec `ebpf:"mochi_stream_recv_enter"`
	MochiStreamRecvExit  *ebpf.ProgramSpec `ebpf:"mochi_stream_recv_exit"`
	MochiStreamSendEnter *ebpf.ProgramSpec `ebpf:"mochi_stream_send_enter"`
	MochiStreamSendExit  *ebpf.ProgramSpec `ebpf:"mochi_stream_send_exit"`
}

// tcpstreamMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type tcpstreamMapSpecs struct {
	Events  *ebpf.MapSpec `ebpf:"events"`
	Pending *ebpf.MapSpec `ebpf:"pending"`
}

// tcpstreamVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type tcpstreamVariableSpecs struct {
}

// tcpstreamObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadTcpstreamObjects or ebpf.CollectionSpec.LoadAndAssign.
type tcpstreamObjects struct {
	tcpstreamPrograms
	tcpstreamMaps
	tcpstreamVariables
}

func (o *tcpstreamObjects) Close() error {
	return _TcpstreamClose(
		&o.tcpstreamPrograms,
		&o.tcpstreamMaps,
	)
}

// tcpstreamMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadTcpstreamObjects or ebpf.CollectionSpec.LoadAndAssign.
type tcpstreamMaps struct {
	Events  *ebpf.Map `ebpf:"events"`
	Pending *ebpf.Map `ebpf:"pending"`
}

func (m *tcpstreamMaps) Close() error {
	return _TcpstreamClose(
		m.Events,
		m.Pending,
	)
}

// tcpstreamVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadTcpstreamObjects or ebpf.CollectionSpec.LoadAndAssign.
type tcpstreamVariables struct {
}

// tcpstreamPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadTcpstreamObjects or ebpf.CollectionSpec.LoadAndAssign.
type tcpstreamPrograms struct {
	MochiStreamRecvEnter *ebpf.Program `ebpf:"mochi_stream_recv_enter"`
	MochiStreamRecvExit  *ebpf.Program `ebpf:"mochi_stream_recv_exit"`
	MochiStreamSendEnter *ebpf.Program `ebpf:"mochi_stream_send_enter"`
	MochiStreamSendExit  *ebpf.Program `ebpf:"mochi_stream_send_exit"`
}

func (p *tcpstreamPrograms) Close() error {
	return _TcpstreamClose(
		p.MochiStreamRecvEnter,
		p.MochiStreamRecvExit,
		p.MochiStreamSendEnter,
		p.MochiStreamSendExit,
	)
}

func _TcpstreamClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed tcpstream_bpfeb.o
var _TcpstreamBytes []byte
