// Code generated by bpf2go; DO NOT EDIT.
//go:build mips || mips64 || ppc64 || s390x

package ebpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type tcpstateSkInfo struct {
	_        structs.HostLayout
	Pid      uint32
	Pad      uint32
	CgroupId uint64
}

// Names of all BPF objects in the ELF.
//
// Used for safe lookups in a Collection or CollectionSpec.
const (
	tcpstateMapEvents                 = "events"
	tcpstateMapSkOwners               = "sk_owners"
	tcpstateProgMochiInetSockSetState = "mochi_inet_sock_set_state"
)

// loadTcpstate returns the embedded CollectionSpec for tcpstate.
func loadTcpstate() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_TcpstateBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load tcpstate: %w", err)
	}

	return spec, err
}

// loadTcpstateObjects loads tcpstate and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*tcpstateObjects
//	*tcpstatePrograms
//	*tcpstateMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadTcpstateObjects(obj any, opts *ebpf.CollectionOptions) error {
	spec, err := loadTcpstate()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// tcpstateSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type tcpstateSpecs struct {
	tcpstateProgramSpecs
	tcpstateMapSpecs
	tcpstateVariableSpecs
}

// tcpstateProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type tcpstateProgramSpecs struct {
	MochiInetSockSetState *ebpf.ProgramSpec `ebpf:"mochi_inet_sock_set_state"`
}

// tcpstateMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type tcpstateMapSpecs struct {
	Events   *ebpf.MapSpec `ebpf:"events"`
	SkOwners *ebpf.MapSpec `ebpf:"sk_owners"`
}

// tcpstateVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type tcpstateVariableSpecs struct {
}

// tcpstateObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadTcpstateObjects or ebpf.CollectionSpec.LoadAndAssign.
type tcpstateObjects struct {
	tcpstatePrograms
	tcpstateMaps
	tcpstateVariables
}

func (o *tcpstateObjects) Close() error {
	return _TcpstateClose(
		&o.tcpstatePrograms,
		&o.tcpstateMaps,
	)
}

// tcpstateMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadTcpstateObjects or ebpf.CollectionSpec.LoadAndAssign.
type tcpstateMaps struct {
	Events   *ebpf.Map `ebpf:"events"`
	SkOwners *ebpf.Map `ebpf:"sk_owners"`
}

func (m *tcpstateMaps) Close() error {
	return _TcpstateClose(
		m.Events,
		m.SkOwners,
	)
}

// tcpstateVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadTcpstateObjects or ebpf.CollectionSpec.LoadAndAssign.
type tcpstateVariables struct {
}

// tcpstatePrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadTcpstateObjects or ebpf.CollectionSpec.LoadAndAssign.
type tcpstatePrograms struct {
	MochiInetSockSetState *ebpf.Program `ebpf:"mochi_inet_sock_set_state"`
}

func (p *tcpstatePrograms) Close() error {
	return _TcpstateClose(
		p.MochiInetSockSetState,
	)
}

func _TcpstateClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed tcpstate_bpfeb.o
var _TcpstateBytes []byte
