// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64 || wasm

package ebpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type tlsplainConnTuple struct {
	_        structs.HostLayout
	Family   uint16
	Sport    uint16
	Dport    uint16
	HasTuple uint8
	Pad      uint8
	Saddr    [16]uint8
	Daddr    [16]uint8
}

type tlsplainGoKey struct {
	_    structs.HostLayout
	Tgid uint32
	Pad  uint32
	G    uint64
}

type tlsplainGoStash struct {
	_     structs.HostLayout
	Obj   uint64
	Buf   uint64
	Tid   uint64
	Bound uint32
	Dir   uint8
	Pad   [3]uint8
}

type tlsplainInflightStash struct {
	_     structs.HostLayout
	Obj   uint64
	Buf   uint64
	Aux   uint64
	Bound uint32
	Dir   uint8
	Kind  uint8
	Ex    uint8
	Pad   uint8
}

type tlsplainObjKey struct {
	_    structs.HostLayout
	Tgid uint32
	Pad  uint32
	Obj  uint64
}

// Names of all BPF objects in the ELF.
//
// Used for safe lookups in a Collection or CollectionSpec.
const (
	tlsplainMapEvents             = "events"
	tlsplainMapGoActive           = "go_active"
	tlsplainMapInflight           = "inflight"
	tlsplainMapTuples             = "tuples"
	tlsplainProgMochiTlsEnter     = "mochi_tls_enter"
	tlsplainProgMochiTlsRecvEnter = "mochi_tls_recv_enter"
	tlsplainProgMochiTlsRet       = "mochi_tls_ret"
	tlsplainProgMochiTlsSendEnter = "mochi_tls_send_enter"
)

// loadTlsplain returns the embedded CollectionSpec for tlsplain.
func loadTlsplain() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_TlsplainBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load tlsplain: %w", err)
	}

	return spec, err
}

// loadTlsplainObjects loads tlsplain and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*tlsplainObjects
//	*tlsplainPrograms
//	*tlsplainMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadTlsplainObjects(obj any, opts *ebpf.CollectionOptions) error {
	spec, err := loadTlsplain()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// tlsplainSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type tlsplainSpecs struct {
	tlsplainProgramSpecs
	tlsplainMapSpecs
	tlsplainVariableSpecs
}

// tlsplainProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type tlsplainProgramSpecs struct {
	MochiTlsEnter     *ebpf.ProgramSpec `ebpf:"mochi_tls_enter"`
	MochiTlsRecvEnter *ebpf.ProgramSpec `ebpf:"mochi_tls_recv_enter"`
	MochiTlsRet       *ebpf.ProgramSpec `ebpf:"mochi_tls_ret"`
	MochiTlsSendEnter *ebpf.ProgramSpec `ebpf:"mochi_tls_send_enter"`
}

// tlsplainMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type tlsplainMapSpecs struct {
	Events   *ebpf.MapSpec `ebpf:"events"`
	GoActive *ebpf.MapSpec `ebpf:"go_active"`
	Inflight *ebpf.MapSpec `ebpf:"inflight"`
	Tuples   *ebpf.MapSpec `ebpf:"tuples"`
}

// tlsplainVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type tlsplainVariableSpecs struct {
}

// tlsplainObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadTlsplainObjects or ebpf.CollectionSpec.LoadAndAssign.
type tlsplainObjects struct {
	tlsplainPrograms
	tlsplainMaps
	tlsplainVariables
}

func (o *tlsplainObjects) Close() error {
	return _TlsplainClose(
		&o.tlsplainPrograms,
		&o.tlsplainMaps,
	)
}

// tlsplainMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadTlsplainObjects or ebpf.CollectionSpec.LoadAndAssign.
type tlsplainMaps struct {
	Events   *ebpf.Map `ebpf:"events"`
	GoActive *ebpf.Map `ebpf:"go_active"`
	Inflight *ebpf.Map `ebpf:"inflight"`
	Tuples   *ebpf.Map `ebpf:"tuples"`
}

func (m *tlsplainMaps) Close() error {
	return _TlsplainClose(
		m.Events,
		m.GoActive,
		m.Inflight,
		m.Tuples,
	)
}

// tlsplainVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadTlsplainObjects or ebpf.CollectionSpec.LoadAndAssign.
type tlsplainVariables struct {
}

// tlsplainPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadTlsplainObjects or ebpf.CollectionSpec.LoadAndAssign.
type tlsplainPrograms struct {
	MochiTlsEnter     *ebpf.Program `ebpf:"mochi_tls_enter"`
	MochiTlsRecvEnter *ebpf.Program `ebpf:"mochi_tls_recv_enter"`
	MochiTlsRet       *ebpf.Program `ebpf:"mochi_tls_ret"`
	MochiTlsSendEnter *ebpf.Program `ebpf:"mochi_tls_send_enter"`
}

func (p *tlsplainPrograms) Close() error {
	return _TlsplainClose(
		p.MochiTlsEnter,
		p.MochiTlsRecvEnter,
		p.MochiTlsRet,
		p.MochiTlsSendEnter,
	)
}

func _TlsplainClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed tlsplain_bpfel.o
var _TlsplainBytes []byte
