// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64 || wasm

package ebpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type udpflowFlowKey struct {
	_      structs.HostLayout
	Family uint8
	Pad    [1]uint8
	Sport  uint16
	Dport  uint16
	Saddr  [16]uint8
	Daddr  [16]uint8
}

type udpflowFlowVal struct {
	_        structs.HostLayout
	Pid      uint32
	Pad      uint32
	CgroupId uint64
	TxBytes  uint64
	LastNs   uint64
}

// Names of all BPF objects in the ELF.
//
// Used for safe lookups in a Collection or CollectionSpec.
const (
	udpflowMapFlows              = "flows"
	udpflowMapOpenEvents         = "open_events"
	udpflowProgMochiUdpSendmsg   = "mochi_udp_sendmsg"
	udpflowProgMochiUdpv6Sendmsg = "mochi_udpv6_sendmsg"
)

// loadUdpflow returns the embedded CollectionSpec for udpflow.
func loadUdpflow() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_UdpflowBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load udpflow: %w", err)
	}

	return spec, err
}

// loadUdpflowObjects loads udpflow and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*udpflowObjects
//	*udpflowPrograms
//	*udpflowMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadUdpflowObjects(obj any, opts *ebpf.CollectionOptions) error {
	spec, err := loadUdpflow()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// udpflowSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type udpflowSpecs struct {
	udpflowProgramSpecs
	udpflowMapSpecs
	udpflowVariableSpecs
}

// udpflowProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type udpflowProgramSpecs struct {
	MochiUdpSendmsg   *ebpf.ProgramSpec `ebpf:"mochi_udp_sendmsg"`
	MochiUdpv6Sendmsg *ebpf.ProgramSpec `ebpf:"mochi_udpv6_sendmsg"`
}

// udpflowMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type udpflowMapSpecs struct {
	Flows      *ebpf.MapSpec `ebpf:"flows"`
	OpenEvents *ebpf.MapSpec `ebpf:"open_events"`
}

// udpflowVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type udpflowVariableSpecs struct {
}

// udpflowObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadUdpflowObjects or ebpf.CollectionSpec.LoadAndAssign.
type udpflowObjects struct {
	udpflowPrograms
	udpflowMaps
	udpflowVariables
}

func (o *udpflowObjects) Close() error {
	return _UdpflowClose(
		&o.udpflowPrograms,
		&o.udpflowMaps,
	)
}

// udpflowMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadUdpflowObjects or ebpf.CollectionSpec.LoadAndAssign.
type udpflowMaps struct {
	Flows      *ebpf.Map `ebpf:"flows"`
	OpenEvents *ebpf.Map `ebpf:"open_events"`
}

func (m *udpflowMaps) Close() error {
	return _UdpflowClose(
		m.Flows,
		m.OpenEvents,
	)
}

// udpflowVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadUdpflowObjects or ebpf.CollectionSpec.LoadAndAssign.
type udpflowVariables struct {
}

// udpflowPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadUdpflowObjects or ebpf.CollectionSpec.LoadAndAssign.
type udpflowPrograms struct {
	MochiUdpSendmsg   *ebpf.Program `ebpf:"mochi_udp_sendmsg"`
	MochiUdpv6Sendmsg *ebpf.Program `ebpf:"mochi_udpv6_sendmsg"`
}

func (p *udpflowPrograms) Close() error {
	return _UdpflowClose(
		p.MochiUdpSendmsg,
		p.MochiUdpv6Sendmsg,
	)
}

func _UdpflowClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed udpflow_bpfel.o
var _UdpflowBytes []byte
